### ISSUE TITLE
종이책 출간 문의

### ISSUE THREAD

**Issue by anemochore** [ratsgo/nlpbook#13]
안녕하세요, 질문이 있습니다. 
종이책은 이미 출판사와 계약이 되어 있나요? 
예정 출간일은 언제쯤일까요?

**Comment by ratsgo** [comment]
안녕하세요 부족한 책인데 관심 가져주셔서 감사합니다.
이지스퍼블리싱이라는 출판사와 계약이 되어 있고요,
이르면 연내 출간을 목표로 하고 있습니다.
막바지 작업 중인데 조만간 공유드릴 수 있을 것 같습니다:)

**Comment by anemochore** [comment]
헛... 네 기다리겠습니다!
