### ISSUE TITLE
4장 150p 웹 서비스 시작하기 관련 문의

### ISSUE THREAD

**Issue by drinkingstraw33** [ratsgo/nlpbook#15]
코드 4-26

`from ratsnlp.nlpbook.classification import get_web_service_app
app = get_web_service_app(inference_fn)
app.run()`

를 실행할 때 url에 접속하면

'Welcome to ngrok!
Before you can serve HTML content, you must sign up for an ngrok account and install your authtoken.'
이라는 경고창이 뜨고 진행되지 않습니다.

**Comment by ratsgo** [comment]
안녕하세요! 혹시 실행 환경이 어떻게 되시나요?
코랩 환경이 아니라면 다음과 같이 해보시겠어요?

```python
from ratsnlp.nlpbook.classification import get_web_service_app
app = get_web_service_app(inference_fn, is_colab=False)
app.run()
```

**Comment by ratsgo** [comment]
안녕하세요, 추가 문의가 들어와 다시 확인해본 결과 다음과 같이 수행해야 웹서비스가 정상적으로 진행됩니다.

- 다음 사이트를 방문해 회원 가입을 하세요 : https://dashboard.ngrok.com/signup
- 다음 사이트를 방문해 로그인 하세요 : https://dashboard.ngrok.com/login
- 다음 사이트를 방문해 인증 토큰을 확인하세요 : https://dashboard.ngrok.com/get-started/your-authtoken
- 예컨대 확인된 인증토큰이 `test111`일 경우 인증토큰을 포함한 다음 커맨드를 코랩에서 실행한 후 웹서비스를 시작하세요

```bash
!mkdir /root/.ngrok2 && echo "authtoken: test111" > /root/.ngrok2/ngrok.yml
```

**Comment by ratsgo** [comment]
코드 개발/책 집필했을 당시엔 위와 같은 조치를 별도로 하지 않아도 실행이 되었던 터라 정상 작동이 되는 줄 알고 있었습니다ㅠㅠ 불편하게 해드려서 죄송합니다. 이에 모든 실습 노트북에 아래와 같은 내용을 추가했습니다.

<img width="1075" alt="스크린샷 2022-01-09 오후 6 10 44" src="https://user-images.githubusercontent.com/26211652/148676426-a572eb1c-9df1-4e98-aca5-fa5771f785e5.png">
