### ISSUE TITLE
P 240 오탈자 신고 / 그림 문의

### ISSUE THREAD

**Issue by kimjisung78** [ratsgo/nlpbook#16]
그림 8-11에는 집(0.75), 책(0.23), 사람(0.02)이라고 표시되어 있는데, 그 아래 내용에는 책(0.75), 집(0.23), 사람(0.02)로 표시되어 있습니다. 어느 것이 맞는 건가요? 그리고 템퍼러쳐 스케일링을 적용해도 확률이 높은 값으로 선택하면 그림 8-11의 "그 책 읽"이 아니라 "그 책 이" 나와야 하는 것 아닌가요?

**Comment by ratsgo** [comment]
@kimjisung78 님 날카로운 지적 감사합니다. 검토 결과 해당 부분은 오타가 맞습니다. 다음은 검토 결과입니다.

우선 8-3절 전체를 관통하는 예제는 다음과 같습니다(그림 8-5).

<img width="601" alt="스크린샷 2021-12-25 오후 1 33 21" src="https://user-images.githubusercontent.com/26211652/147377475-77e5a77d-dc46-4aab-aa96-938487bf4324.png">

이를 바탕으로 한다면 그림 8-8과 237페이지 설명은 다음과 같이 정정되어야 할 것 같습니다(그림은 이미 수정된 결과이며 텍스트 수정 내용은 볼드 표시)

> 그런데 샘플링(sampling)이라는 방식도 있습니다. 샘플링 방식 예를 든 다음 그림을 보면 그라는 컨텍스트를 입력했을 때 모델은 다음 토큰으로 **책(0.5), 집(0.4)**, 사람(0.1)이 그럴듯하다고 예측했습니다. 여기에서 다음 토큰을 확률적으로 선택합니다. **책**이 선택될 가능성이 50%로 제일 크고 사람이 선택될 가능성도 10%로 작지만 없지 않습니다. 복권 당첨 확률이 아주 낮지만 당첨되는 사람이 나오는 것과 비슷합니다.

<img width="500" alt="스크린샷 2021-12-25 오후 1 28 30" src="https://user-images.githubusercontent.com/26211652/147377510-50cfed0e-405c-4251-8b68-e6ce39b09b4a.png">

말씀주신 그림 8-11과 240페이지 설명은 다음과 같이 정정되어야 합니다(그림은 이미 수정된 결과이며 텍스트 수정은 없음)

> 다음 그림은 그림 8-5에서 템퍼러처 스케일링을 적용한 예시입니다. 원래대로(그림 8-5)라면 그 다음 토큰 확률은 각각 책(0.5), 집(0.4), 사람(0.1)이었습니다. 템퍼러처 스케일링을 적용한 결과 그 확률이 책(0.75), 집(0.23), 사람(0.02)으로 바뀌었습니 다. 마찬가지로 그 책 다음 토큰 확률도 각각 이(0.4), 을(0.3), 읽(0.3)에서 이(0.6), 을(0.2), 읽(0.2)으로 바뀌었습니다. 순위는 변하지 않았지만 원래 컸던 확률은 더 커지고, 작았던 확률은 더 작아져 확률 분포의 모양이 뾰족(sharp)해졌음을 알 수 있습니다.

<img width="500" alt="스크린샷 2021-12-25 오후 1 44 14" src="https://user-images.githubusercontent.com/26211652/147377570-42915486-d087-49f3-8834-2d579654d5ee.png">

**Comment by kimjisung78** [comment]
제가 순간 잘못 이해한 줄 알았습니다. 해당 부분은 다음 쇄에 반영해주시면 좋을 것 같습니다. 집필하신 블로그와 책 덕분에 많이 공부 해왔고, 덕분에 많은 부분 이해가 되어 감사합니다.
