### ISSUE TITLE
GPT 바이트 수준 BPE 병합 우선순위

### ISSUE THREAD

**Issue by JulieOnIsland** [ratsgo/nlpbook#17]
안녕하세요.

2장 BPE 관련해서 질문이 있습니다.

45쪽에서 BPE 어휘 집합 구축하기에서는 토큰을 바이그램 쌍으로 빈도를 계산해서 병합 우선순위를 결정했습니다.

​
그런데 실습에서 (55쪽) 한글을 유니코드 바이트로 변환하고 병합 우선순위를 보면 문자 길이가 다양합니다.

바이트 기준 BPE를 적용하면 문자 길이가 다양해질 수 있는 건가요? 즉 앞에서처럼 바이그램(2개)가 아니라 여러 개의 길이로 나뉘어서 빈도를 계산하게 되는건가요?

​

답변 부탁드리겠습니다! 
감사합니다.

**Comment by ratsgo** [comment]
@JulieOnIsland 님, 질문 주셔서 감사드립니다. 결론만 말씀드리면 문자 기준 BPE를 수행하든, 바이트 기준 BPE를 하든 문자 길이는 다양해질 수 있을 것 같습니다.

45쪽에 소개한 내용은 문자 기준의 BPE입니다. 두 개씩 묶어서 병합합니다. 예컨대 다음과 같습니다.

- a, b, c, d, e
- a, b, cd, e
- a, bcd, e

위의 예시를 보면 c와 d가 병합되었고, 그다음은 b와 cd가 병합되었습니다. 다시 말해 서로 병합되는 문자 길이가 다양합니다.

55쪽에 소개한 내용은 바이트 기준 BPE입니다. 이 역시 두 개씩 묶어서 병합합니다. 예컨대 다음과 같습니다.

-  ì, ķ, Ī, ë, ħ
-  ì, ķ, Īë, ħ
-  ì, ķĪë, ħ

위의 예시를 보면 Ī와 ë가 병합되었고, 그다음은 ķ와 Īë가 병합되었습니다. 이 역시 서로 병합되는 문자 길이가 다양합니다.

**Comment by JulieOnIsland** [comment]
@ratsgo 답변 감사합니다! :-)
