### ISSUE TITLE
4장 문서에 꼬리표 달기 - 학습 마친 모델을 실전 투입하기 질문

### ISSUE THREAD

**Issue by KyeoRaeHan** [ratsgo/nlpbook#20]
안녕하세요.

책 보면서 막히는 부분이 있어서 글남깁니다.

책에 적혀있는대로 실습을 한 후, 마지막 웹 서비스 시작하기 단계에서

링크가 Running on http://127.0.0.1:5000/ <<이거 하나만 뜨는데, 

왜 그러는건가요??

**Comment by vickhanmailnet** [comment]
저도 그 부분에서 에러가 발생했습니다.
Development mode 에서 실행해야 하는데 Production mode 에서 실행되고 있다고 connection이 안된다는 뜻인 것 같습니다.
Flask 에서 헤ㅐ당 실습 앱을 작동시킬 수 있는 다른 방법이 있을까요?

**Comment by ratsgo** [comment]
안녕하세요 @vickhanmailnet 님 대신 답변해주셔서 감사합니다. 코랩 환경이 책 집필 이후에도 변화 무쌍하게 바뀌는 관계로, 원고와 다른 부분이 벌써 발생하였군요. 불편을 드려 죄송합니다.

제가 방금 전에 다시 한번 코랩 환경에서 4장 문서 분류의 인퍼런스 코드를 확인한 결과 @vickhanmailnet 님께서 설명한 방식대로 정상적으로 동작함을 확인하였습니다. 코랩 노트북에도 이미 반영되어 있습니다만, 다음 절차대로 수행하시면 됩니다(구글 크롬 브라우저 기준).

**1. ngrok 회원가입**

- 다음 사이트(그림)를 방문해 회원 가입을 하세요 : https://dashboard.ngrok.com/signup
- 이미 회원 가입을 완료했다면 이 절차는 건너뛰어도 됩니다.

<img width="250" alt="스크린샷 2022-02-20 오후 1 19 41" src="https://user-images.githubusercontent.com/26211652/154828401-82f6f8e5-30aa-4027-9a0a-b4f884cbf837.png">


**2. ngrok 로그인**

- 다음 사이트(그림)를 방문해 로그인 하세요 : https://dashboard.ngrok.com/login

<img width="250" alt="스크린샷 2022-02-20 오후 1 19 48" src="https://user-images.githubusercontent.com/26211652/154828418-89a330b0-b809-4693-a5c1-4e075d8c892b.png">


**3. ngrok 인증 토큰 확인**

- 다음 사이트(그림)를 방문해 인증 토큰을 확인하세요 : https://dashboard.ngrok.com/get-started/your-authtoken
  - 그림 예시의 경우 확인된 인증 토큰은 `23SB9(생략)`입니다.

<img width="1266" alt="스크린샷 2022-02-20 오후 1 18 51 복사본" src="https://user-images.githubusercontent.com/26211652/154828464-582b0496-f50d-45da-ad9a-63f04c247bf0.png">


**4. 인증 토큰을 코랩에 저장**

- 인증토큰을 포함한 다음 커맨드를 코랩에서 실행하세요.

```bash
!mkdir /root/.ngrok2 && echo "authtoken: 23SB9(생략)" > /root/.ngrok2/ngrok.yml
```

**5. 웹서비스 시작하기**

- 다음 커맨드를 코랩에서 실행하세요.

```python
from ratsnlp.nlpbook.classification import get_web_service_app
app = get_web_service_app(inference_fn)
app.run()
```

**Comment by ratsgo** [comment]
**동작 예시**

- 다음은 구글 크롬 브라우저 기준 동작 예시입니다.

<img width="700" alt="스크린샷 2022-02-20 오후 1 47 53 복사본" src="https://user-images.githubusercontent.com/26211652/154828796-2e6de91c-2462-4bc7-bdac-18246d108a38.png">


- 위 그림 예시에서 `http://{your-infomation}.ngrok.io/`를 클릭하면 웹서비스에 접속할 수 있습니다.
- 구글 크롬 브라우저의 경우 해당 주소에 접속하면 다음과 같은 경고창이 뜹니다.

<img width="500" alt="스크린샷 2022-02-20 오후 1 47 04" src="https://user-images.githubusercontent.com/26211652/154828811-a9c5f932-a995-43f5-aa21-5b42f99683cb.png">

- 위 그림에서 `세부정보`를 클릭하면 다음과 같은 정보가 뜹니다.

<img width="500" alt="스크린샷 2022-02-20 오후 1 47 10" src="https://user-images.githubusercontent.com/26211652/154828818-d311bdb1-975e-42e1-bd8a-55b369a495f7.png">

- 위 그림에서 `이 안전하지 않은 사이트를 방문`을 클릭하면 다음과 같이 웹서비스에 접속할 수 있습니다.

<img width="500" alt="스크린샷 2022-02-20 오후 1 47 39" src="https://user-images.githubusercontent.com/26211652/154828827-450993e5-4cf3-4bc0-998e-e4f8447a83fd.png">

**Comment by vickhanmailnet** [comment]
p{margin-top:0;margin-bottom:0}
    


    회답해 주셔서 감사합니다.
아마도 ngrok 회원가입 후에 이메일주소 인증을 하지 않아서 그래서, 보안인증 단계가 완전하지 않아서
ngrok 로 app(inference_fn) 웹서비스 요청이 제대로 안 되었던 것 같습니다. 지금은 잘 작동하고 있습니다.
BERT 와 GPT 에 대해서 이해하기 쉽게 집필해 주셔서 매우 감사드립니다.

--------- 원본 메일 ---------

    
        보낸사람: gichang.lee ***@***.***>
        받는사람: ratsgo/nlpbook ***@***.***>
        
            참조: coevol ***@***.***>, Mention ***@***.***>
        
        날짜: 22.02.20 13:36 GMT +0900
        제목: Re: [ratsgo/nlpbook] 4장 문서에 꼬리표 달기 - 학습 마친 모델을 실전 투입하기 질문 (Issue #20)
        
        
    
    
        
안녕하세요 @vickhanmailnet 님 대신 답변해주셔서 감사합니다. 코랩 환경이 책 집필 이후에도 변화 무쌍하게 바뀌는 관계로, 원고와 다른 부분이 벌써 발생하였군요. 불편을 드려 죄송합니다.
제가 방금 전에 다시 한번 코랩 환경에서 4장 문서 분류의 인퍼런스 코드를 확인한 결과 @vickhanmailnet 님께서 설명한 방식대로 정상적으로 동작함을 확인하였습니다. 코랩 노트북에도 이미 반영되어 있습니다만, 다음 절차대로 수행하시면 됩니다(구글 크롬 브라우저 기준).
1. ngrok 회원가입

다음 사이트(그림)를 방문해 회원 가입을 하세요 : https://dashboard.ngrok.com/signup
이미 회원 가입을 완료했다면 이 절차는 건너뛰어도 됩니다.


2. ngrok 로그인

다음 사이트(그림)를 방문해 로그인 하세요 : https://dashboard.ngrok.com/login


3. ngrok 인증 토큰 확인

다음 사이트(그림)를 방문해 인증 토큰을 확인하세요 : https://dashboard.ngrok.com/get-started/your-authtoken

그림 예시의 경우 확인된 인증 토큰은 23SB9(생략)입니다.




4. 인증 토큰을 코랩에 저장

인증토큰을 포함한 다음 커맨드를 코랩에서 실행하세요.

!mkdir /root/.ngrok2 && echo "authtoken: 23SB9(생략)" > /root/.ngrok2/ngrok.yml
5. 웹서비스 시작하기

다음 커맨드를 코랩에서 실행하세요.

from ratsnlp.nlpbook.classification import get_web_service_app
app = get_web_service_app(inference_fn)
app.run()
