### ISSUE TITLE
4장 문서에 꼬리표 달기 - 학습 마친 모델을 실전 투입하기 중 질문

### ISSUE THREAD

**Issue by sehooni** [ratsgo/nlpbook#21]
안녕하세요! 자연어처리를 공부하고 있는 학생입니다.
책을 참고하면서 직접 코랩노트북에 코드를 작성하면서 공부를 진행하고 있는데,
p149 4단계 부분에서 부정(positive)이 서술되어 있는 부분을 발견했습니다.

이 부분이 오 기술되어 있는 것일까요? 
아니면 부정 위치일 때 해당 문장이 부정이나(긍정으로 인식), 반대일 때 긍정이나(긍정으로 인식) 이 되도록 pred값을 만든다는 것일까요?

**Comment by sehooni** [comment]
깃허브 내 정오표에도 서술이 되어있지 않아 이렇게 질문을 남깁니다. 감사합니다!

**Comment by sehooni** [comment]
아 코드를 구현하면서 이해가 되었습니다. 부정일 때 부정으로, 긍정일 때 긍정으로 표시되도록 한다는 설명인데 오타였던 것 같습니다.

**Comment by ratsgo** [comment]
안녕하세요 @sehooni 님, 이슈를 늦게 확인했네요. 확인한 결과 말씀주신 것처럼 오타가 맞습니다. 출간 전에 몇 번 확인했는데도 오타가 남아 있네요. 혼란을 드려 죄송합니다. 정오표에도 반영하였습니다. 감사합니다.
