### ISSUE TITLE
Chapter4. 4-4 모델환경설정 사전 작업 이슈

### ISSUE THREAD

**Issue by kyjna0312** [ratsgo/nlpbook#22]
Chapter4. [4-4 모델환경설정 사전 작업]에서 실행 문제가 발생하였습니다

`
import torch
from ratsnlp.nlpbook.classification import ClassificationTrainArguments

args = ClassificationTrainArguments(
    pretrained_model_name="beomi/kcbert-base",
    downstream_corpus_name="nsmc",
    downstream_model_dir="/content/drive/MyDrive/BERTandGPT/Chapter4",
    batch_size=32 if torch.cuda.is_available() else 4,
    learning_rate=5e-5,
    max_seq_length=128,
    epochs=3,
    tpu_cores=0 if torch.cuda.is_available() else 8,
    seed=7,
)
`

기존의 코드를 그대로 실행하면 아래와 같은 에러 메세지가 출력됩니다 (경로는 제 활동에 맞게 변경하였습니다)
ImportError: /usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at13_foreach_erf_EN3c108ArrayRefINS_6TensorEEE

리서치 결과, colab의 일부 설정 변경에 따라 사전에 pip install 과정이 필요하게 되었습니다
(출처 : https://github.com/pytorch/xla/issues/3215)
`
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.9-cp37-cp37m-linux_x86_64.whl

!pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchtext==0.10.0 -f https://download.pytorch.org/whl/cu111/torch_stable.html
`

해당 작업이 생각보다 시간이 걸리므로 런타임에 유의하셔야 합니다
위의 pip install 과정을 마친 후 정상 작동을 확인하였습니다

**Comment by sputnik7565** [comment]
Chapter4. [4-4 모델환경설정 사전 작업]에서 문제가 있습니다.

from ratsnlp.nlpbook.classification import ClassificationTrainArguments
실행시

ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/data.py)

에러가 발생합니다.

**Comment by ratsgo** [comment]
코랩 환경이 변화무쌍하게 바뀌면서 의존성 패키지들 문제가 생긴 것 같네요.
의존성 문제를 해결한 ratsnlp 1.0.5를 배포하였습니다.
지금은 `pip install ratsnlp`만 입력해도 실행이 가능한 상태입니다.
