### ISSUE TITLE
4-3 학습 마친 모델을 실전 투입하기 - 웹 서비스 구현 오류

### ISSUE THREAD

**Issue by joinmateFirst** [ratsgo/nlpbook#23]
안녕하세요.
책 내 예재를 수행하던 중에 진행이 안 되는 부분이 있어서 문의를 남깁니다. 
ngrok 쪽의 문제 인거 같긴한데 해결책을 찾을수가 없네요.

![image](https://user-images.githubusercontent.com/102345075/160061858-a777150c-1a43-48aa-b1e2-148c42b8e183.png)

**Comment by joinmateFirst** [comment]
위 문제의 원인에 대해서 우연하게 알게 되었는데, 방화벽이 있어서 ngrok 쪽에 접속이 안 되어서 그런거 같습니다. 
네트워크를 바꿔서 하니깐 정상적으로 동작을 하네요.

**Comment by ratsgo** [comment]
앗 답이 늦어서 죄송합니다. 해결이 되었다니 다행입니다!
