### ISSUE TITLE
ner-train-colab.ipynb 튜토리얼에 대하여

### ISSUE THREAD

**Issue by wwjhang** [ratsgo/nlpbook#27]
안녕하세요 좋은 코드 및 지식 공유해주셔서 무한한 감사드립니다. 다름이 아니라 튜토리얼 따라서 쭉 해보다가 train.txt 와 val.txt에 자체 데이터셋 넣어서 해보려고 했는데 (형식은 원래와 같이 하였습니다)
학습 데이터 셋 구성에서 자체 txt파일 크기가 너무 큰지 (7G가량) python이 killed되어버리고 진행이 안되는데 
혹시 이 부분 어떻게 해결할 수 있을까요?

**Comment by ratsgo** [comment]
@wwjhang 님 안녕하세요, 답이 너무 늦었습니다. 해당 문제는 코랩 환경의 리소스(램) 크기 문제로, 제가 아는 한 고급 옵션을 구독하시는 경우 더 큰/좋은 리소스를 할당받을 수 있습니다. 당장의 해결은 처리 대상 데이터 크기를 줄이거나, 고급 옵션을 구독하는 방안이 현실적일 것 같습니다^^; 큰 도움이 못되어 송구스럽습니다.
