### ISSUE TITLE
4장 문서에 꼬리표 달기 환경설정 이슈에 대해 문의드립니다.

### ISSUE THREAD

**Issue by Gyeongmin-Baek** [ratsgo/nlpbook#31]
from ratsnlp.nlpbook.classification import ClassificationTrainArguments
이 현재 안되는거 같습니다.

오류 메시지 : ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/data.py)

어떻게 해결하면 좋을까요?

**Comment by ratsgo** [comment]
코랩 환경이 변화무쌍하게 바뀌면서 의존성 패키지들 문제가 생긴 것 같네요ㅠㅠ
불편 드려 죄송합니다.
의존성 문제를 해결한 ratsnlp 1.0.5를 배포하였습니다.
지금은 `pip install ratsnlp`만 입력해도 실행이 가능한 상태입니다.
처음부터 다시 수행해보시겠어요?

**Comment by Gyeongmin-Baek** [comment]
감사합니다. 해결되었습니다!
