### ISSUE TITLE
특강을 해주실수 있나요

### ISSUE THREAD

**Issue by urigachi** [ratsgo/nlpbook#32]
연구원들과 파이썬 학습을 하고 있습니다.
GPT3 실습으로 전문가 특강을 해 주실수 있는지요?

**Comment by ratsgo** [comment]
@urigachi 님 제가 뭐라고, 특강까지 생각해주셔서 감사할 따름입니다ㅠㅠ
직장인인지라 시간을 많이 못내는데다 실력도 부족해서 특강은 아무래도 무리일거 같습니다^^;
부족한 게 많은데 다시 한번 감사드립니다.
