### ISSUE TITLE
1-1 설정값 선언

### ISSUE THREAD

**Issue by alextn00** [ratsgo/nlpbook#34]
안녕하세요, 책 보고 실습코드 따라하던 중 오류가 생겨 문의드립니다.
저는 코랩에서 실행하고 있고, 
`!pip install ratsnlp`
`!pip install tensorflow`
`!pip install torch`
한 이후에 실습 코드 1-1을 실행하니 

```
from ratsnlp.nlpbook.classification import ClassificationTrainArguments
args = ClassificationTrainArguments(
    pretrained_model_name = "beomi/kcbert-base",
    downstream_corpus_name = "nsmc",
    downstream_corpus_root_dir = "/root/Korpora",
    downstream_model_dir = "/gdrive/My Drive/nlpbook/checkpoint-doccls",
    learning_rate = 5e-5,
    batch_size = 32,
)
```

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-6-be74e4d58540> in <module>()
      1 #!pip install torchmetrics==0.7.3
----> 2 from ratsnlp.nlpbook.classification import ClassificationTrainArguments
      3 args = ClassificationTrainArguments(
      4     pretrained_model_name = "beomi/kcbert-base",
      5     downstream_corpus_name = "nsmc",

32 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/resource_handle_pb2.py in <module>()
    148   ,
    149   'DESCRIPTOR' : _RESOURCEHANDLEPROTO,
--> 150   '__module__' : 'tensorflow.core.framework.resource_handle_pb2'
    151   # @@protoc_insertion_point(class_scope:tensorflow.ResourceHandleProto)
    152   })

SystemError: google/protobuf/pyext/descriptor.cc:358: bad argument to internal function

이런 오류가 뜨는데 구글링을 해봐도 해결이 되지 않아 문의드립니다.

**Comment by ratsgo** [comment]
안녕하세요, 코랩 환경 변화에 따라 해당 오류가 생긴 것 같습니다^^; 불편 드려 죄송합니다.
방금 전에 의존성 패키지 버전을 업데이트해 두었습니다. 
코랩 노트북을 처음 연 뒤 `!pip install ratsnlp`를 실행하고 나서 코드 1-1을 실행해보시겠어요?

**Comment by alextn00** [comment]
오오 이제 실행됩니다!! 감사합니다!!
