### ISSUE TITLE
[Do it 자연어 처리] 코드 오류 문의드립니다. 

### ISSUE THREAD

**Issue by yhlee1627** [ratsgo/nlpbook#37]
교재 206페이지의 아래 트레이너 정의를 하였을 때
trainer = nlpbook.get_trainer(args)
다음과 같은 에러가 나옵니다.

---------------------------------------------------------------------------
MisconfigurationException                 Traceback (most recent call last)
[<ipython-input-29-7c6e0a07330b>](https://localhost:8080/#) in <module>()
----> 1 trainer = nlpbook.get_trainer(args)

4 frames
[/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py](https://localhost:8080/#) in _set_parallel_devices_and_init_accelerator(self)
    513             ]
    514             raise MisconfigurationException(
--> 515                 f"{self.accelerator.__class__.__qualname__} can not run on your system"
    516                 " since the accelerator is not available. The following accelerator(s)"
    517                 " is available and can be passed into `accelerator` argument of"

MisconfigurationException: TPUAccelerator can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].

혹시 어떻게 해결하면 될까요?
답변 부탁드립니다.

**Comment by ratsgo** [comment]
@yhlee1627 님 안녕하세요, 제 환경에서는 재현이 어렵네요ㅠㅠ
혹시 코랩 런타임 유형은 어떻게 지정하셨을까요? 가급적 GPU로 지정하시길 권해드립니다. 아울러 TPU 관련 패키지는 설치하지 않으시길 부탁드립니다.
마지막으로 런타임 유형을 GPU로 하셨다면 `QATrainArguments`에서 `tpu_cores=0`(다음 그림처럼 지정)으로 지정해보시고 실행하시면 더욱 확실할 것 같습니다.

<img width="500" alt="스크린샷 2022-07-26 오전 12 39 45" src="https://user-images.githubusercontent.com/26211652/180818851-498aeca7-a64a-4947-b460-95ad39e5c30e.png">
