### ISSUE TITLE
4-3. 영화리뷰 감성분석 웹서비스 만들기 실습중인데 에러가 발생합니다. 부탁드립니다.

### ISSUE THREAD

**Issue by bighit2020** [ratsgo/nlpbook#38]
코드 4-18인퍼런스를 설정하다가 downstream_model_dir="~~/checkpoint-doccls"에 문제가 발생했습니다. colab환경이 제것의 위치 무문제 없는것 같은 유효하지 않다고 합니다. 절대경로가 맞다고 생각하는데요..
<img width="1096" alt="simple" src="https://user-images.githubusercontent.com/52269286/180639423-08f40237-5cd3-4cd6-80c3-d01ff35f0e61.png">
.

**Comment by bighit2020** [comment]
해결 했습니다. --- 앞에 실습 완성한 내용을 그대로 복사 하니까 에러가 없습니다.

**Comment by bighit2020** [comment]
다시  에러가 뜹니다.  중간 착오가 있었던것 같습니다.

**Comment by ratsgo** [comment]
다음 이슈가 발생한 원인과 동일한 것으로 보입니다.
해결 방안은 다음을 참고하세요.

- https://github.com/ratsgo/nlpbook/issues/39#issuecomment-1194173612
