### ISSUE TITLE
6-3.개체명인식웹서비스만들기 에서도 같은 부분의 경로 파일을 찾지 못합니다.

### ISSUE THREAD

**Issue by bighit2020** [ratsgo/nlpbook#39]
<img width="977" alt="2022-07-25_23-27-37" src="https://user-images.githubusercontent.com/52269286/180801652-dfec8ab7-aa79-42ae-984c-c45d5a452368.png">
경로상의 파일에 ckpt 파일 있어할것 같은데 없어서 그런같기도 합니다. 해결 부탁드립니다.

**Comment by ratsgo** [comment]
안녕하세요 @bighit2020 님, 불편 드려 죄송합니다.
제가 방금 전에 제 환경에서 개체명인식 모델을 학습하고 해당 코드라인을 실행한 결과 정상 동작함을 확인했습니다.

<img width="800" alt="스크린샷 2022-07-26 오전 12 03 55" src="https://user-images.githubusercontent.com/26211652/180810528-48447b49-ffac-41b2-84e6-6f2783c073ad.png">

위 코드가 정상 동작한 배경에는 `/gdrive/My Drive/nlpbook/checkpoint-ner`에 해당하는 파일 목록이 다음과 같기 때문입니다 (제 구글 드라이브 기준).

<img width="400" alt="스크린샷 2022-07-26 오전 12 04 42" src="https://user-images.githubusercontent.com/26211652/180813111-887f8c7f-c6de-4330-ac08-8874d7662820.png">

**Comment by ratsgo** [comment]
제 생각엔 @bighit2020 님께서 개체명 인식 모델을 학습할 때 경로를 다음과 같이 입력한 것으로 보이는데요.

- /content/drive/Mydrive/Doit_Natural/nlpbook/checkpoint-ner

코랩 환경에서는 `/content` 이하의 디렉토리는 코랩의 로컬을 의미하는 것으로 알고 있습니다. 코랩의 로컬은 @bighit2020 님께서 사용하시던 코랩 런타임을 종료하는 경우 모든 결과가 지워집니다. 학습 결과를 코랩 환경에 저장했기 때문에 코랩 런타임 종료와 동시에 학습 결과가 사라진 것으로 보입니다.

따라서 학습 결과는 @bighit2020 님의 구글 드라이브(코랩 런타임을 종료하더라도 결과가 사라지지 않음)에 저장하는 것이 좋겠습니다. 이에 학습하실 때 `NERTrainArguments`의 `downstream_model_dir`를 반드시 `/gdrive` 하위로 지정(예컨대 `/gdrive/My drive/Doit_Natural/nlpbook/checkpoint-ner`, 여기에서 `My Drive`는 공백을 살림)하셔야 합니다. 그래야 문제를 피할 수 있을 것 같습니다.
