### ISSUE TITLE
4장, 8장 ratsnlp 관련

### ISSUE THREAD

**Issue by argetan** [ratsgo/nlpbook#43]
안녕하세요 작가님 덕분에 많이 배우고 있습니다.

다만 실습을 따라가던 도중에 몇가지 문제가 생겨 연락드립니다.

1. from ratsnlp.nlpbook.generation import GenerationTrainArguments
 from ratsnlp.nlpbook.classification import ClassificationTrainArguments
8장, 4장에 나오는 GenerationTrainArguments, ClassificationTrainArguments를 import하는 과정에서 ImportError가 발생합니다.

ImportError: /usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl7stridesEv

NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

진행환경은 코랩에서 진행하였고, 이에 대한 대응으로 ratsnlp 문서를 찾아 읽어보았습니다. 과정에서
from ratsnlp.nlpbook.classification.arguments import ClassificationTrainArguments 로 문서에 나와있어 진행했으나, 동일한 문제가 발생하였고, 이후 torch의 문제라는 이야기도 있어 !pip install mmcv-full -f 를 통해 업데이트를 했으나 동일한 문제가 지속되고 있어 문의드립니다. 

항상 많은 도움 감사합니다.

**Comment by ratsgo** [comment]
@argetan 님 답이 너무 늦어서 죄송합니다. 해당 문제는 `ratsnlp`가 의존하는 파이썬 패키지 문제로 보이는데요, 현재는 의존성 문제가 해결된 것으로 보입니다. 코랩 노트북을 처음부터 다시 시작해 `!pip install ratsnlp`을 수행하신 뒤 `GenerationTrainArguments`나 `ClassificationTrainArguments`을 다시 import 하면 문제가 사라질 것으로 예상됩니다. 혹시 문제가 여전히 발생하는 경우 다시 말씀주시면 바로 검토해보겠습니다. 다시 한번 불편 드려 죄송합니다.
