### ISSUE TITLE
4-3 웹서비스 시작하기

### ISSUE THREAD

**Issue by dioryiiy** [ratsgo/nlpbook#55]
최근에 등록된 답변(웹서비스 실행오류)을 참고하여

새로운 네이버메일로 ngrok도 다시 가입하여 메일 인증도 다시하고

코드를 다시 실행시켰는데 

여전히 한문장 밖에 뜨지 않습니다..

Serving Flask app 'ratsnlp.nlpbook.classification.deploy'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000/
INFO:werkzeug:Press CTRL+C to quit
Exception in thread Thread-18:
Traceback (most recent call last):

도움 부탁드립니다 

감사합니다

**Comment by dioryiiy** [comment]
아 다시시작 및 모두 실행을 하니 정상 작동하네요! 감사합니다

**Comment by ratsgo** [comment]
해결되었다니 다행입니다! 부족한 책에 관심 가져주셔서 감사합니다.
