### ISSUE TITLE
5-3 학습 마친 모델 실전 투입에서 웹서비스 실행시 ERR_NGROK_6022 이 뜨네요.ㅠ.ㅠ

### ISSUE THREAD

**Issue by icon001** [ratsgo/nlpbook#56]
![image](https://user-images.githubusercontent.com/38023210/233559768-3b0ce27b-7e08-445e-afff-72c20eb8dc4d.png)
![image](https://user-images.githubusercontent.com/38023210/233559801-030ea4ea-052a-4586-b7c5-b06e9c11e517.png)

참고로 4-3에서는 정상적으로 웹서비스가 실행 되어서 테스트까지 완료 하였습니다.

ngrok.yml 파일을 확인해 보면 다음과 같이 인증키는 잘 설정 되어 있습니다.
![image](https://user-images.githubusercontent.com/38023210/233560367-77006fdd-d723-426f-b363-4f75e234e47f.png)

먼가 다른 작업을 해 주어야 하는지 궁금합니다. 제가 아직까지 ngrok가 어떤식으로 동작을 하는지 이해를 못해서요.ㅠ.ㅠ

**Comment by icon001** [comment]
ngrok.yml 파일을 삭제 했다가 다시 재생성하니까 사용이 가능하네요.ㅠ.ㅠ
아마 authtoke: (여기서 한칸 띄워줘야 되는건가 보네요.)2II~ 이렇게 생성하니까 되었습니다.^^

**Comment by ratsgo** [comment]
해결되었다니 다행입니다! 부족한 책에 관심 가져주셔서 감사합니다.
